# Generated by Django 4.2.7 on 2023-11-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "auctions",
            "0002_remove_user_name_alter_user_id_alter_user_password_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
