# Generated by Django 4.2.7 on 2023-11-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.CharField(default="", max_length=350),
            preserve_default=False,
        ),
    ]
