# Generated by Django 4.2.7 on 2023-11-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0010_alter_listing_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="category",
            field=models.CharField(default="Cloth", max_length=64),
        ),
        migrations.AddField(
            model_name="listing",
            name="desc",
            field=models.CharField(
                default="This is a really good product", max_length=350
            ),
        ),
    ]
